# Generated by Django 6.0.4 on 2026-04-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
